# Generated by Django 5.0.6 on 2024-06-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='Comment')),
                ('published_date', models.DateTimeField(auto_now_add=True, verbose_name='Published Date')),
            ],
        ),
    ]
