# Generated by Django 5.0.7 on 2024-08-31 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='github_url',
            field=models.URLField(blank=True, help_text='Provide a valid GitHub profile URL.', max_length=255, null=True, validators=[django.core.validators.URLValidator()], verbose_name='GitHub URL'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='Provide a valid LinkedIn profile URL.', max_length=255, null=True, validators=[django.core.validators.URLValidator()], verbose_name='LinkedIn Url'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='website_url',
            field=models.URLField(blank=True, help_text='Provide a valid website URL.', max_length=255, null=True, validators=[django.core.validators.URLValidator()], verbose_name='Website Url'),
        ),
    ]
