# Generated by Django 5.0.7 on 2024-09-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_saved_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='saved_by',
        ),
    ]
