# Generated by Django 5.0.7 on 2024-09-09 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_saved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='saved_by',
            field=models.ManyToManyField(blank=True, related_name='saved_posts', through='blog.SavedPost', to=settings.AUTH_USER_MODEL, verbose_name='Saved By'),
        ),
    ]
